image: node:lts

before_script:
  - npm install --cache .npm --prefer-offline

pages:
  only:
    - main
  artifacts:
    paths:
      - public
  variables:
    SITE: $CI_PAGES_URL
    BASE: $CI_PROJECT_NAME
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - public/
      - .npm/
      - node_modules/
  script:
    - echo "What is the $(locale)"
    - npm run build
