image: node:lts

before_script:
  - npm install

pages:
  only:
    - main
  artifacts:
    paths:
      - public
  variables:
    - SITE: $CI_PAGES_URL
    - BASE: $CI_PROJECT_NAME
  script:
    - npm run build
