# npx netlify-cms-proxy-server
local_backend: true

site_url: "https://mtvbarfelde.netlify.app"
locale: "de"
backend:
  name: git-gateway
  branch: main

slug:
  encoding: "ascii"
  clean_accents: true

publish_mode: simple
media_folder: "src/assets/"
public_folder: "../../assets/"
show_preview_links: false
editor:
  preview: false

collections:
  - name: pages
    label: Seiten
    label_singular: Seite
    files:
      - name: index
        label: Startseite / Aktuelles
        file: src/pages/index.md
        fields:
          - name: layout
            widget: hidden
            default: "@layouts/IndexLayout.astro"
          - name: main_heading
            label: Große Überschrift Startseite
            widget: string
            default: Aktuelles
          - name: body
            label: Text auf der Startseite
            widget: markdown
          - name: events_heading
            label: Überschrift Veranstaltungen
            widget: string
          - name: events
            label: Veranstaltungen
            label_singular: Veranstaltungen
            widget: list
            fields:
              - name: date
                label: Datum, Uhrzeit
                widget: string
              - name: name
                label: Name
                widget: string
      - name: ueber-uns
        label: Über uns ...
        file: src/pages/ueber-uns.md
        fields:
          - name: layout
            widget: hidden
            default: "@layout/BasePageLayout.astro"
          - name: body
            label: Text auf der "Über uns..." Seite
            widget: markdown

  - name: bericht
    label: Berichte
    label_singular: Bericht
    folder: src/content/berichte/
    create: true
    summary: "{{title}} ({{day}}.{{month}}.{{year}})"
    sortable_fields: [date]
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - {
          label: "Titelbild",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Text", name: "body", widget: "markdown" }
