# npx netlify-cms-proxy-server
local_backend: true

site_url: "https://mtvbarfelde.netlify.app"
logo_url: "https://mtvbarfelde.netlify.app/wappen.png"
locale: "de"
backend:
  name: github
  repo: janheini/mtv-astro
  branch: main

slug:
  encoding: "ascii"
  clean_accents: true

publish_mode: simple
media_folder: "src/assets"
public_folder: "@assets"
show_preview_links: false
editor:
  preview: false

collections:
  - name: ueber-uns
    label: Aktuelles / Über uns
    files:
      - name: index
        label: Startseite / Aktuelles
        file: src/pages/index.md
        fields:
          - name: main_heading
            label: Große Überschrift Startseite
            widget: string
            default: Aktuelles
          - name: body
            label: Text auf der Startseite
            widget: markdown
          - name: events_heading
            label: Überschrift Veranstaltungen
            widget: string
          - name: events
            label: Veranstaltungen
            label_singular: Veranstaltungen
            widget: list
            fields:
              - name: date
                label: Datum, Uhrzeit
                widget: string
              - name: name
                label: Name
                widget: string
      - name: ueber-uns
        label: Über uns ...
        file: src/pages/ueber-uns/index.md
        fields:
          - name: body
            label: Text auf der "Über uns..." Seite
            widget: markdown
      - name: alles-auf-einen-blick
        label: Alles auf einen Blick
        file: src/pages/ueber-uns/alles-auf-einen-blick.md
        fields:
          - name: body
            label: Text auf der "Alles auf einen Blick" Seite
            widget: markdown
      - name: meldung-von-sportunfaellen
        label: Sportversicherung
        file: src/pages/ueber-uns/meldung-von-sportunfaellen.md
        fields:
          - name: body
            label: Text auf der "Meldung von Sportunfällen / Sportversicherung" Seite
            widget: markdown

  - name: hsg09
    label: HSG 09
    files:
      - name: hsg09
        label: HSG 09 Startseite
        file: src/pages/hsg09/index.md
        fields:
          - name: body
            label: Text auf der HSG 09 Startseite
            widget: markdown
      - name: hsg09-vorstand
        label: HSG 09 Vorstand
        file: src/pages/hsg09/vorstand-hsg09.md
        fields:
          - name: body
            label: Text auf der "Vorstand HSG 09" Seite
            widget: markdown
      - name: hsg09-trainingszeiten
        label: HSG 09 Trainingszeiten
        file: src/pages/hsg09/trainingszeiten.md
        fields:
          - name: body
            label: Text auf der "Trainingszeiten HSG 09" Seite
            widget: markdown

  - name: sporthaus
    label: Sporthaus
    files:
      - name: unser-sporthaus
        label: Unser Sporthaus
        file: src/pages/unser-sporthaus/index.md
        media_folder: "/src/assets/sporthaus"
        public_folder: "@assets/sporthaus"
        fields:
          - name: title
            label: Überschrift
            required: true
            widget: string
          - name: hero
            label: Titelbild
            required: false
            widget: image
            collapsed: false
            hint: |
              Wird zwischen Überschrift und Text angezeigt
              und bei verlinkten Berichten auch auf der Startseite
          - name: body
            label: Text auf der "Unser Sporthaus"
            widget: markdown
          - name: gallery
            label: Bildergalerie unten
            label_singular: Bild
            widget: list
            required: false
            collapsed: false
            field:
              name: image
              label: Bild
              widget: image
      - name: sporthaus-preise
        label: Sporthaus Miete / Preise
        file: src/pages/unser-sporthaus/preise.md
        fields:
          - name: body
            label: Text auf der "Sporthaus Miete / Preise" Seite
            widget: markdown
      - name: sporthaus-belegungsplan
        label: Sporthaus Belegungsplan
        file: src/pages/unser-sporthaus/belegungsplan.md
        fields:
          - name: body
            label: Text auf der "Sporthaus Belegungsplan" Seite
            widget: markdown

  - name: sportarten
    label: Sportarten
    label_singular: Sportart
    folder: src/pages/sportarten
    media_folder: "/src/assets/sportarten"
    public_folder: "@assets/sportarten"
    summary: "{{title}}"
    fields:
      - name: title
        label: Name
        widget: string
      - name: hero
        label: Titelbild
        widget: image
      - name: body
        label: Text
        widget: markdown

  - name: berichte
    label: Berichte
    label_singular: Bericht
    folder: src/content/berichte
    create: true
    summary: "{{title}} ({{day}}.{{month}}.{{year}})"
    sortable_fields: [date]
    fields:
      - name: title
        label: Titel
        widget: string
      - name: author
        label: Author
        widget: string
        required: false
      - name: hero
        label: Titelbild
        widget: image
        required: false
        description: Wird auf der Startseite angezeigt, wenn dort verknüpft
      - name: date
        label: Datum
        widget: datetime
      - name: body
        label: Text
        widget: markdown
        required: false
      - name: gallery
        label: Bildergalerie unten
        label_singular: Bild
        widget: list
        required: false
        collapsed: false
        field:
          name: image
          label: Bild
          widget: image
